### ISSUE TITLE
iProov Demo URL not working.

### ISSUE THREAD

**Issue by Thomas678** [iProov/html5#3]
Hi iProov,

We tried the following demo URL at customer's office and encountered problem.

https://demo.iproov.com/govtech/

The problem:
After typing in the user id: 0003@iproov.com, the allow camera screen will show up and won't go away. Please see screen below....

![image](https://user-images.githubusercontent.com/53250149/63259781-ec3e0c00-c2b1-11e9-8125-cb4a5d41ae50.png)

The environment:
- The Chrome ver. is 67.0.3396.99
![image](https://user-images.githubusercontent.com/53250149/63259505-278c0b00-c2b1-11e9-8bef-0e0193f4419f.png)

- Camera has been allowed in Chrome.

Additional info.:
- We noticed iProov was trying to connect http://www.iproov.com and it resulted in 'ERR_TUNNEL_CONNECTON_FAILED' and jquery error. Please see screenshot below...
![image](https://user-images.githubusercontent.com/53250149/63260184-d41abc80-c2b2-11e9-850f-225341b03fe6.png)

Questions:
1. What could be the reason for the behavior?
2. Is the jquery accessing the library internally or link(s) in internet?
3. Is there any other websites that needs to be whitelisted?

Thanks,
Thomas Teo

**Comment by Thomas678** [comment]
Just to add that customer already whitelisted the following websites:-
https://demo.iproov.com/govtech/
https://demo.iproov.com/

**Comment by GlenHughes** [comment]
This issue has now been resolved.
